# Generated by Django 5.2.6 on 2025-09-27 07:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientsubmission',
            name='data',
        ),
        migrations.CreateModel(
            name='FormField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('field_type', models.CharField(max_length=50)),
                ('required', models.BooleanField(default=False)),
                ('form_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='onboarding.formversion')),
            ],
        ),
        migrations.CreateModel(
            name='ClientSubmissionData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField()),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submission_data', to='onboarding.clientsubmission')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onboarding.formfield')),
            ],
        ),
    ]
